// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footerWrapper: string;
export const footer: string;
export const small: string;
export const madeBy: string;
export const notice: string;
