// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const article: string;
export const header: string;
export const title: string;
export const contexts: string;
export const publishDate: string;
export const control: string;
export const separator: string;
export const link: string;
export const notLink: string;
