// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const subSection: string;
export const title: string;
export const avatar: string;
export const avatarImage: string;
export const name: string;
export const links: string;
export const description: string;
export const list: string;
