// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const imageWrapper: string;
export const image: string;
export const name: string;
export const links: string;
export const description: string;
