// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const card: string;
export const cardContent: string;
export const cardTitle: string;
export const cardBody: string;
export const publishDate: string;
export const tags: string;
