// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const hero: string;
export const image: string;
export const details: string;
export const title: string;
export const content: string;
