// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const top: string;
export const logoContent: string;
export const descriptionContent: string;
