// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const articleList: string;
export const title: string;
export const link: string;
export const meta: string;
