// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const navigation: string;
export const navigationItem: string;
export const logoLink: string;
export const logo: string;
